### ISSUE TITLE
ClientID

### ISSUE THREAD

**Issue by martynwendon** [scanno/nl.scanno.mqtt#1]
Hey there,

Any chance of adding the ClientID to the settings & MQTT connect options?

I use ClientID as an additional security measure on all my brokers :-)

Thanks!

Martyn

**Comment by scanno** [comment]
Hi Martyn, 

Working on it. 
Already changed the default client id to homey_<id>. 
Only need to do the settings to override the default value. That is the most work.

**Comment by scanno** [comment]
Implemented in
ec065c3dddb3283884127a34e05d59e927335596

**Comment by martynwendon** [comment]
That's awesome :-)

I'm a bit new to Homey, how can I install the version from github instead of the App Store version?  Or will the App Store version get updated automatically, if so how long does that take?


Martyn

**Comment by scanno** [comment]
I have a request pending to have a new version published in the app store as beta version that includes the client ID change. This will take a few days. As soon as it is published, homey will update the app automatically. If you have the stable version installed, you will have to install the beta version (because I always publish a new version as beta first and promote it to stable one week later if there are no problems) 

If you can't wait, then do a git clone and use the athom cli to install it yourself.
