### ISSUE TITLE
URGENT! Flows created with MQTT has been disabled, bacuse flow executed too many times!

### ISSUE THREAD

**Issue by talzac** [scanno/nl.scanno.mqtt#20]
! URGENT ! 
Hi,
It seems that version 2.0 have som new bug that disables the MQTT flows, bacuse flow executed too many times. Please, please check this out, now I can not use MQTT at all... 
! URGENT !

**Comment by scanno** [comment]
Sorry, nothing I can do here. Athom put a rate limit on the triggers. So complain there.

**Comment by talzac** [comment]
You have to change the MQTT update, so that it does not update so often?

**Comment by scanno** [comment]
> You have to change the MQTT update, so that it does not update so often?

And how should I do that? Say you have 10 cards to receive something from a topic. Each message that arrives sends a trigger. That trigger starts a loop so I can check if there is a card that should be fired because the topic matches. That means 10 triggers in one second without even one flow actually getting fired. 

Sorry can't change that. Complain to Athom because that is the way it should be done according to their api.

**Comment by talzac** [comment]
so.. they just destroyed this app? thanks athom....

**Comment by talzac** [comment]
I found this new rules: 
Max trigger 10 times/second or 120 times/minute.
2.0.5-rc.3

**Comment by scanno** [comment]
Yes, so with 11 flows with a trigger card (even with different topics) will disable all flows as soon as one message arrives.

Like I said blame Athom. Can't do anything here.

**Comment by scanno** [comment]
Next firmware update from Homey should solve the problem.

**Comment by talzac** [comment]
Thanks! I deviced to go for virtual devices and MQTT hubb until this is solved.
