### ISSUE TITLE
Client reports broker unavailable

### ISSUE THREAD

**Issue by AdyRock** [scanno/nl.scanno.mqtt#9]
Since the 2.1.1 client update I see a message in the home screen log saying "The MQTT broker is unavailable" approximately 1 per day.

Homey V2-rc9.

**Comment by scanno** [comment]
Are you using Cloudmqtt as broker?

**Comment by AdyRock** [comment]
It's a local broker running on a Raspberry Pi. I set it up about 6 months ago and can't get to it right now so I can't remember which one. 
I also have Domoticz running on the Pi and use the MQTT to synchronise between Domoticz and Homey.

**Comment by scanno** [comment]
Hmm. I have updated the mqtt client library that I use to the latest version.
But the the connection between the client and server is really gone, otherwise that message would not appear.

I will release a new version next week where you will be able to set the keepalive time. That is the interval that the client sends a signal that its still available. Currently it's 10 seconds and that might be too short.

I don't have the problem myself on the Mqtt broker for Homey, so there is something with the network connection in homey itself.

**Comment by AdyRock** [comment]
Ok. Maybe the drop out has always been there but just not reported before. 
The raspberry Pi is hard wired to the network and I'm sure that is stable but maybe the WiFi has an occasional drop out.
